id   = "relay-b"
port = 4002

[telemetry]
enabled        = true
server_ws_url  = "ws://127.0.0.1:8080/ingest"
interval_sec   = 10

[[pqkds]]
port                 = 3020
sae_id               = "ba"
remote_sae_id        = "ab"
remote_proxy_address = "http://127.0.0.1:4001"
kme_address          = "http://127.0.0.1:11003"

[[pqkds]]
port                 = 3021
sae_id               = "bc"
remote_sae_id        = "cb"
remote_proxy_address = "http://127.0.0.1:4003"
kme_address          = "http://127.0.0.1:11004"
