id   = "relay-a"
port = 4001

[telemetry]
enabled        = true
server_ws_url  = "ws://127.0.0.1:8080/ingest"
interval_sec   = 10

[[pqkds]]
port                 = 3010
sae_id               = "ab"
remote_sae_id        = "ba"
remote_proxy_address = "http://127.0.0.1:4002"
kme_address          = "http://127.0.0.1:11001"

[[pqkds]]
port                 = 3011
sae_id               = "ac"
remote_sae_id        = "ca"
remote_proxy_address = "http://127.0.0.1:4003"
kme_address          = "http://127.0.0.1:11002"
