id   = "relay-c"
port = 4003

[telemetry]
enabled        = true
server_ws_url  = "ws://127.0.0.1:8080/ingest"
interval_sec   = 10

[[pqkds]]
port                 = 3030
sae_id               = "ca"
remote_sae_id        = "ac"
remote_proxy_address = "http://127.0.0.1:4001"
kme_address          = "http://127.0.0.1:11005"

[[pqkds]]
port                 = 3031
sae_id               = "cb"
remote_sae_id        = "bc"
remote_proxy_address = "http://127.0.0.1:4002"
kme_address          = "http://127.0.0.1:11006"
