proxies = [{ sae_id = "Validator_1SAE", addr = "http://127.0.0.1:4002" }]
port = 4001
port_etsi = 3001
local_sae_id = "Test_2SAE"
remote_sae_id = "Test_1SAE"
remote_proxy_address = "http://127.0.0.1:4000"
kme_address = "http://172.16.0.155:8082"
#targets_sae_id = ["Validator_2SAE", "Validator_3SAE", "Debina_1SAE", "BobSAE"]
ca_cert = "./qbck-ca.crt"
client_cert = "./client.crt"
client_key = "./client.key"
