proxies = []
port = 4000
port_etsi = 3000
local_sae_id = "Test_1SAE"
remote_sae_id = "Test_2SAE"
remote_proxy_address = "http://127.0.0.1:4001"
kme_address = "http://172.16.0.154:8082"
#targets_sae_id = ["Validator_2SAE", "Validator_3SAE", "Debina_1SAE", "BobSAE"]
ca_cert = "./qbck-ca.crt"
client_cert = "./client.crt"
client_key = "./client.key"
