proxies = [{ sae_id = "Validator_1SAE", addr = "http://127.0.0.1:4002" }]
port = 4003
port_etsi = 3003
local_sae_id = "Validator_2SAE"
remote_sae_id = "Validator_1SAE"
kme_address = "https://31.182.67.99:8082"
remote_proxy_address = "http://127.0.0.1:4002"
ca_cert = "./qbck-ca.crt"
client_cert = "./client.crt"
client_key = "./client.key"
