version: '3.9'

services:
  pqkd-relay:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: pqkd-relay
    working_dir: /app
    command: ["pqkd-relay", "-c", "config.toml", "-t", "mesh.toml"]
    volumes:
      - ./config.toml:/app/config.toml
      - ./mesh.toml:/app/mesh.toml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
