network_id = "pqkd-example-network"

[[relay]]
id    = "relay-warsaw"
pqkds = ["warsaw-berlin", "warsaw-paris"]

[[relay]]
id    = "relay-berlin"
pqkds = ["berlin-warsaw", "berlin-paris"]

[[relay]]
id    = "relay-paris"
pqkds = ["paris-warsaw", "paris-berlin"]

[[connection]]
first      = "relay-warsaw"
second     = "relay-berlin"
first_sae  = "warsaw-berlin"
second_sae = "berlin-warsaw"

[[connection]]
first      = "relay-warsaw"
second     = "relay-paris"
first_sae  = "warsaw-paris"
second_sae = "paris-warsaw"

[[connection]]
first      = "relay-berlin"
second     = "relay-paris"
first_sae  = "berlin-paris"
second_sae = "paris-berlin"
